services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=wua
      - POSTGRES_USER=wua
      - POSTGRES_PASSWORD=wua
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - db:/opt/lib/postgresql/data
  bot:
    build:
      dockerfile: ./Dockerfile
    env_file:
      - .env
      - .env.secrets
  migrate:
    build:
      dockerfile: ./migrate.Dockerfile
    
volumes:
  db: 