"""wua

Revision ID: 69606844ff5f
Revises: 
Create Date: 2024-09-26 20:38:07.607776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69606844ff5f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wuas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('wu_size', sa.Integer(), nullable=False),
    sa.Column('a_size', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('chat', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wuas')
    # ### end Alembic commands ###
